### ISSUE TITLE
是否支持cloudflare 管理的域名

### ISSUE THREAD

**Issue by baymax55** [joyqi/acme-bot#1]

**Comment by joyqi** [comment]
支持啊，用 `dns_cf` 即可 https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_cf

**Comment by baymax55** [comment]
> 支持啊，用 `dns_cf` 即可 https://github.com/acmesh-official/acme.sh/wiki/dnsapi#dns_cf

好的,谢谢,我先试试看
